### ISSUE TITLE
Blender 2.8 addon won´t be recognized

### ISSUE THREAD

**Issue by cglukas** [p2or/blender-renderborder#1]
Blender 2.8 addon won´t be recognized unless the folder contains a 

`"__init__.py"`

 script

**Comment by p2or** [comment]
Hi @cglukas,

you don't need that extra file. Just download `render-border.py` file, open up the *User Preferences > Addons*, click *Install* and select `render-border.py`. Instructions: https://github.com/p2or/blender-renderborder#installation

Cheers,
Christian
