### ISSUE TITLE
Update for 2.8

### ISSUE THREAD

**Issue by Phaidonas** [p2or/blender-renderborder#2]
Will you update it for 2.8, i can not find the properties

**Comment by p2or** [comment]
Hi @Phaidonas,

already done that. Download the latest release from [here (py file)](https://github.com/p2or/blender-renderborder/releases) and install it via user preferences. 

Tested with the latest Blender 2.8x version 1min ago. If that doesn't work for you for any reason, please provide more infos. Thanks. 

Cheers,
Christian
