### ISSUE TITLE
Render Border addon not activated in blender 3.1.0

### ISSUE THREAD

**Issue by Pablinimaxd** [p2or/blender-renderborder#3]
Hi there!

First of all thank you for this amazing addon which I have used since blender 2.8. Unfortunately the addon is already installed in the blender 3.1.0 last update but I can't activate it, I mean it shows in the camera properties but I can't click to activate it. Any ideas? Thanks!

<img width="302" alt="Captura de Pantalla 2022-03-20 a la(s) 17 53 19" src="https://user-images.githubusercontent.com/92812221/159189978-6c1879b6-e9a3-4701-9bb4-145a365b8636.png">

**Comment by p2or** [comment]
Hi @Pablinimaxd,

thanks for your report. I already fixed this a few months ago (8723e0908591ab21c4d07e7b36f2a89dced8a1a9), but haven't released a _new version_ yet so thanks for the reminder. Just 'Remove' your current version of the addon in the 'Preferences', download the [latest release for 3.1](https://github.com/p2or/blender-renderborder/releases/latest), install the downloaded `.py` file, activate it and everything should work as before. A trusty gif:

![ezgif-2-227b029221](https://user-images.githubusercontent.com/512368/159220598-e933a881-aed5-4fbe-b54b-0c6825a48aa1.gif)

Cheers
Christian

**Comment by Pablinimaxd** [comment]
Amazing! Thanks and great work as well...
