### ISSUE TITLE
duplicate camera

### ISSUE THREAD

**Issue by AlexFundorin** [p2or/blender-renderborder#4]
Hi. Nice addon. I have a question. 
Let's say I have a 1080x1080 canvas that's already rendered.
And I have a camera that's set up properly.
Now I need to render region animations, so that they could be overlayed on top of the main canvas in post.
So, I select region and I want a new camera to be created, with lens size adjusted to that region and shiftXY values. 
The copied camera should have the same coordinates as the original one and, maybe, a new name, like "%Original_camera_name%_%top_left_coordinates%_%new_resolution%". Is it to much to ask?

**Comment by AlexFundorin** [comment]
One other suggestion: can you put the addon settings into the render tab, rather than camera?
It's much faster to reach the render tab when you already have some other object selected and the cameras folder hidden in the outliner, rather than enabling any camera visibility, selecting it and then navigating to the cam tab. Thanks in advance.

**Comment by p2or** [comment]
Hi Alex,

sounds good to me... As explained in the [gotchas section](https://github.com/p2or/blender-renderborder#gotchas) you'd have to use e.g. python or [loom](https://github.com/p2or/blender-loom) to get the border update properly. For formatting the output path I'd recommend Loom as well since it supports [global variables](https://github.com/p2or/blender-loom/issues/9#issuecomment-636003959) within the output file path. Just add a new one in the user preferences like `$YourVariableName` and assign e.g. `bpy.context.scene.renderborder.max_x` to get `R` or ` bpy.context.scene.renderborder.max_y` to get `T` and you can use it in the regular output filepath:

<img width="478" alt="Screenshot 2022-03-30 at 17 09 40" src="https://user-images.githubusercontent.com/512368/160869801-e786c425-22ce-4fd0-9969-7b1422448af4.png">

The camera name is one of the built-ins so `/tmp/$CAMERA_$BMX-$BMY_` as shown above evaluates to `Camera_1920-1080_####.png` and should do the trick: 

<img width="498" alt="Screenshot 2022-03-30 at 17 23 33" src="https://user-images.githubusercontent.com/512368/160871666-e2587a34-c9cc-4c7d-bb97-db15eec8003d.png">

Cheers,
Christian

**Comment by AlexFundorin** [comment]
Thanks, Christian. I already checked out Loom.
For my tasks it's more convenient to have separate cameras for each region, so that I could render them separately, afterwards.
RenderBorder is still useful to me, cause I'm able to get XY region dimension from it as a target resolution for additional camera copies. I still need to shiftXY each of them manually and fiddle with the camera matrix size to match the borders, but, still better than purely guessing everything.

**Comment by p2or** [comment]
Hi @AlexFundorin,

> For my tasks it's more convenient to have separate cameras for each region, so that I could render them separately, afterwards.

_Blender_ stores the render region data per scene. For _multiple cameras_ along with different values for the render region you would have to create a new scene for each camera, unfortunately (I'm also not a fan of that logic).

However, we could _extend the add-on_ and allow multiple cameras along with different render regions in one scene. Would even be a nice improvement IMHO. Problem is that we have to rewrite the code, store and re-store the user data per camera, detect when the user switches the camera, detect if a camera is assigned to a marker etc. I personally don't have the time to do that and test all that cases right now but we can put it on the _to-do list_ if this is somewhat useful to _other users too_... I recommend open up a new issue to keep it organized, explain in detail why this is useful and in best case someone else picks it up in the meantime.

Cheers,
Christian

**Comment by AlexFundorin** [comment]
I wonder, if it's a Loom specific issue should it be a part of the renderborder? I'm using a separate addons to render animation sequences from multiple cameras, but if it's all can be collected in one place, that would be nice.

**Comment by p2or** [comment]
Hi @AlexFundorin,

it's a limitation of _Blender_ that we can not have multiple cameras along with different region values in one scene.  However, we can extend the _render border add-on_ to allow that.

Cheers,
Christian

**Comment by AlexFundorin** [comment]
Oh, but can we have a button inside the addon that would convert the active camera to the region render, including main resolution, sensor size and shiftXY? Sort of like "apply modifier", but for an addon. Then, a user could duplicate the main camera, beforehand, and have a cropped camera that would match the main one.

**Comment by p2or** [comment]
Hi @AlexFundorin,

same problem - the resolution and aspect ratio settings are saved per scene. Creating a button that "bakes" the selected region into a new camera shouldn't be a problem, but the render resolution and such is tied to the actual scene and thus it would be the same for each rendering (camera).

Hopefully blender developers will realize that such settings should be tied to the _camera_ rather than the actual scene...

Cheers,
Christian

**Comment by AlexFundorin** [comment]
I mean, it can still be useful in the following scenario.
One has the main camera and the resolution of 1920x1080.
He crops region to a point of interest in the scene., using renderborder. Presses the "realize camera" button.
Blender creates new camera with with the shiftXY values and sensor size adjusted. New camera name contains original camera name, top left corner position and resolution of the region.
One sets main resolution back to 1920x1080 and creates a new region to make another camera, using renderborder addon.
It's all happening in the same scene.
Then, later, if he wants to, one can duplicate the existing scene as many times as he wants and set up cameras from the "copied" pool of cams, using the info from their names. Or, he can manually change the main resolution, based on that same info and switching the cameras.
P.S. Sorry if I might be annoying, saying the same thing over and over.

**Comment by p2or** [comment]
Hi @AlexFundorin,

agree that it might be useful to some degree. However, storing `XRYT` in the name of the camera and having the user manually type in the pixel values each time before rendering is just a workaround and not a real solution IMHO.

_The solution_ would be that _Blender_ finally allows the user to _override the render settings per camera_ by default, which should ideally be done in C/C++ and would solve a lot of problems for all kinds of rendering workflows and yours too. I have been waiting for years, let's see :) 

Cheers,
Christian

**Comment by p2or** [comment]
... oops, just noticed that I completely missed your second comment @AlexFundorin. 

I created a [new branch](/p2or/blender-renderborder/tree/output-panel) and moved the panel to the output properties to test the changes. Just download the `py` file from [there](/p2or/blender-renderborder/tree/output-panel) and install as add-on or override the regular one. If you have the time, please test it extensively and report back whether that works.

Also, you can create a shortcut to open up the panel as a popover. I'd suggest add a new key to _3D View > 3D View (Global) > Object Mode > Object Mode (Global)_, identifier would be `wm.call_panel` and the name is `RBORDER_PT_camera`.

![Screenshot-2022-03-31-at-16 23 37](https://user-images.githubusercontent.com/512368/161084260-7ed54011-e7d2-4c5a-b6a6-59e7e2dd121e.jpg)

Cheers,
Christian

**Comment by ChameleonScales** [comment]
You might be interested in this add-on which does pretty much exactly what the OP asks (among other things):
source code: https://gitlab.com/ChameleonScales/camera_regions
video (slightly older version): https://odysee.com/@ChameleonScales:c/blender-camera-regions-tutorial
BA thread: https://blenderartists.org/t/add-on-camera-regions/682526

Note: my add-on doesn't conflict with this one. You can use both at the same time.

**EDIT:** I'm an idiot.
I didn't notice the OP was the same person I was talking to in private.

**Comment by ChameleonScales** [comment]
I'm an idiot.
I didn't notice the OP was the same person I was talking to in private.
